### ISSUE TITLE
regcool uses URL without the version

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#1004]
### Details

regcool uses a URL without the version and breaks with updates. See the last daily run.

**Comment by emtuls** [comment]
For some reason, it seems that when we don't pass in a checksum, chocolately automatically attempts to validate the checksum of the newly downloaded file against the checksum of the previous package stored in the cache in our sources.
![image](https://github.com/mandiant/VM-Packages/assets/35854880/e6a9bd11-95c4-4492-855c-f71ee80dc5d6)


Because we don't want to force all packages to ignore checksums, we could attempt to add `$env:ChocolateyIgnoreChecksums = $true` to the top of the code (inside the `try-catch`) and this will act as if we set `--ignore-checksums` for the specific package, and allows it to work as intended.

**Comment by Ana06** [comment]
@emtuls did you want to add this package to the default config? :thinking:
