### ISSUE TITLE
Package proposal: git.vm

### ISSUE THREAD

**Issue by stevemk14ebr** [mandiant/VM-Packages#1038]
### Package Name

git

### Tool Name

git

### Package type

SINGLE_EXE

### Is the tool a console application?

false

### Version

2.45.0

### Category

Utilities

### Tool's authors

Git for Windows

### Tool's description

Git for Windows

### Download URL

https://github.com/git-for-windows/git/releases/download/v2.45.0.windows.1/Git-2.45.0-64-bit.exe

### Download SHA256 Hash

7694a2118ac80146636be1ee751ee81d2aea7e9106d29dd8fed06c32cff0c59f

### Why is this tool a good addition?

Essential developer tool, required for NPM to function correctly

**Comment by Ana06** [comment]
There is a [`git`](https://community.chocolatey.org/packages/git) community package: `choco install git`. As I do not see the benefit of a link in the tools folder, I think we do not need a custom package in this repository.

@stevemk14ebr 
> required for NPM to function correctly

What do you exactly mean with this? What is exactly the issue? should we add [`git`](https://community.chocolatey.org/packages/git) as dependency for another package?

**Comment by stevemk14ebr** [comment]
![image](https://github.com/mandiant/VM-Packages/assets/6619205/fe3c3185-619c-45da-8dcf-6a301abe7555)

**Comment by Ana06** [comment]
This is interesting because `git` was not needed to install any of the packages we are installing with `npm`. For example `npm install -g obfuscator-io-deobfuscator` works without any issues. The [npm installation documentation](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm) doesn't mention `git as dependency, although it is mentioned in the [common errors page](https://docs.npmjs.com/common-errors). :confused: 
![image](https://github.com/mandiant/VM-Packages/assets/16052290/110203af-d8dd-4881-bed3-97646413464c)

We can add `git` as dependency of `nodejs.vm`. We can also add a package for js-deobfuscator, it should be easy after https://github.com/mandiant/VM-Packages/pull/1042 is merged.

**Comment by Ana06** [comment]
I have just opened a PR to add `git` as dependency of `nodejs.vm`. I'll create a package for `js-deobfuscator` after https://github.com/mandiant/VM-Packages/pull/1042 and https://github.com/mandiant/VM-Packages/issues/999.
