### ISSUE TITLE
dokan fails to install in the daily run

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#1063]
### Details

dokan fails to install in the daily run with the following error:
```
ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\Tools\Dokan\Dokan_x64.msi" /qn /norestart ] was not successful. Exit code was '1603'. Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\dokan.vm_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error..
The upgrade of dokan.vm was NOT successful.
```
Although it was working on https://github.com/mandiant/VM-Packages/pull/1053. I think the issue is that we are missing the [`validExitCodes` we use in `VM-Install-With-Installer`](https://github.com/mandiant/VM-Packages/blob/165ec34682f7cb5356d0e8e51a29e0cc2f9df54b/packages/common.vm/tools/vm.common/vm.common.psm1#L732C12-L732C44) in the dokan code. @naacbin would you like to try to fix this (as it is related to your latests PRs)?

**Comment by naacbin** [comment]
I can check when I have some time, but I'm not sure its related to `validExitCodes`, even if this could help. I think the problem comes from the forced install of `dokan.vm`. In the pipeline `dokan.vm` is first installed as dependency for `arsenalimagemounter.vm` (which works from the daily pipeline) and then the installation is forced for `dokan.vm` again. As the package is already present the MSI throw the error you highlighted.

**Comment by naacbin** [comment]
Closing as #1068 as been merged.
