### ISSUE TITLE
duplication when opening application from taskbar

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#1100]
### Details

when starting fakenet, chrome, and processExplorer and IDA from the taskbar, I get a duplication which is confusing: 
![image](https://github.com/mandiant/VM-Packages/assets/16052290/17dadc4a-f0a8-4f84-8475-a46d9d2994ad)

@emtuls I think this is related to some things you have worked on. Do you have any ideas how to fix it?

**Comment by emtuls** [comment]
@Ana06 
I am not sure if this can be completely fixed unfortunately.

**Unable to be fixed:**
- For the `IDA` shortcut, because our shortcut is to a launcher, it is technically not the same program that is being run (it launches the correct IDA), so that is why it's creating a whole new icon.
- For `Cyberchef`, we are using a shortcut that launches `chrome`, and because the shortcut itself is not actually `chrome`, it will create a new icon as well, as it is not the actual program that is being run.
  - **Alternatively:** I can make the shortcut be just to open up a `.html` page, which gets us closer (once the default application for `.html` is properly done), but this would not allow us to pin a shortcut to the taskbar because Microsoft does not allow pinning of a `.html` pages to a taskbar, but it does work for a desktop icon and in the `Tools` directory.

**Fixable:**
- For `Procmon` and `Procexp`, I can fix them, since it seems that our shortcuts are to the 32 bit versions and they must detect that it is running on a 64 bit system and then spawns the 64 bit version, which is a separate application and thus, creates a new icon. Changing these to just run the 64 bit programs directly mitigates this.

**Unsure**
-  For `Fakenet`, I did not experience this issue on my system, so I would need to investigate further. Would you be able to provide me  the Target your `fakenet` is using for the shortcut?

**Comment by Ana06** [comment]
@emtuls can you please send a PR to fix procmon and procexp now (that seem easy to fix) and we can continue discussing the rest here?

the chrome issue is related to https://github.com/mandiant/VM-Packages/pull/1054, as this would again make it look a bit different. 

Have you tested the latest version of fakenet?

**Comment by Ana06** [comment]
procmon and procexp should be fixed now.

**Comment by Ana06** [comment]
# Proposal to fix Chrome/CyberChef

## Option 1: Use the CyberChef icon in the taskbar for Chrome

Use the CyberChef icon in the taskbar for Chrome that by default opens CyberChef:

![image](https://github.com/user-attachments/assets/945682ff-4438-4999-b9b4-0e06ec617452)

1. In the `cyberchef.vm` package, change the target of `CyberChef.lnk` to "C:\Program Files\Google\Chrome\Application\chrome.exe" -home "C:\Tools\CyberChef\CyberChef_v10.19.0.html"

**Note that this option makes that Chrome always uses the CyberChef icon in the taskbar**. 


## Option 2: Use the Chrome icon in the taskbar for Chrome that by default opens CyberChef

1. In the `googlechrome.vm` package, create a shortcut in `%ProgramData%\_VM\Google Chrome.lnk` with Chrome as target an icon.
1. In the `cyberchef.vm` package, modify `%ProgramData%\_VM\Google Chrome.lnk` target to C:\Program Files\Google\Chrome\Application\chrome.exe" -home "C:\Tools\CyberChef\CyberChef_v10.19.0.html`
1. Change `LayoutModification.xml` in flare-vm to use `%ProgramData%\_VM\Google Chrome.lnk`

--
Note that both solutions make Google Chrome a hard dependency of CyberChef, not being able to remove the dependency as proposed in https://github.com/mandiant/VM-Packages/issues/1021. I think this is ok and I think we can still fix the `.html` popup issue as part of https://github.com/mandiant/VM-Packages/issues/1021 that @emtuls has researched.

**Comment by Ana06** [comment]
After doing some more testing on option 1, it seems that Windows that not consistenly group Chrome and CyberChef until I reboot the system, but I think this is acceptable.
