### ISSUE TITLE
Add Windbg

### ISSUE THREAD

**Issue by mr-tz** [mandiant/VM-Packages#252]

**Comment by Ana06** [comment]
## IDEA: load symbols
Load `explorer.exe`, it will take some time (~30min), but will load many symbols so that you don't have to wait when working on other samples. 
We can use [`.reload /f`](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/-reload--reload-module-).

Not sure if it should be part of the windbg.vm package or something like windbg.symbols.vm (so that we make downloading symbols optional).

**Comment by Ana06** [comment]
Maybe one of these packages also include windbg preview

**Comment by Ana06** [comment]
We could also use the installer at https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger

It looks like there is no preview anymore: https://twitter.com/timmisiak/status/1646748737195347968?cxt=HHwWgMDQrY3QttotAAAA

**Comment by mr-tz** [comment]
https://github.com/TimMisiak/windup
