### ISSUE TITLE
Package idea: ipython

### ISSUE THREAD

**Issue by mr-tz** [mandiant/VM-Packages#286]
https://ipython.org/

likely just add to https://github.com/mandiant/VM-Packages/blob/main/packages/libraries.python3.vm/tools/modules.xml

**Comment by Ana06** [comment]
@mr-tz can you provide some context why you think this library is useful?

**Comment by mr-tz** [comment]
It's a powerful interactive shell.

**Comment by Ana06** [comment]
I tried to install IPython with `py -3.10 -m pip install ipython  --disable-pip-version-check` (similarly as we do in `VM-Pip-Install`) but afterwards I am only able to run it with `py -3.10 -m IPython`, but not with `ipython`. @mandiant/vms any ideas what the issue is?

@mandiant/vms opinions on adding this library?

**Comment by Menn1s** [comment]
Hi Ana, I just tested that command on ARM Win 11 and ipython installed and worked by running `ipython`.

For context this was a fresh install and I pretty much only installed python3 so I could test that out.
