### ISSUE TITLE
Fix shortcut icon for .py and .bat files

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#675]
`VM-Install-From-Zip` is being used for `.py` and `.bat` files, but the icon in the shortcut doesn't seem to work well in these cases. 

Related https://github.com/mandiant/VM-Packages/issues/674

**Comment by Ana06** [comment]
@emtuls this issue is related to other issues you have worked on recently. Would you like to work on it? 😄

**Comment by emtuls** [comment]
@Ana06 Sure thing! Do you have any examples of which ones do this and what should their icon's be?

A quick look for `Python` ones show: `ida.diaphora.vm` and `didier-stevens-beta/suite.vm` and I noticed this about these packages:
- `ida.diaphora.vm` is not intended to be run as a python script directly, so I'm not sure if we want to modify this?
- `didier-stevens-beta/suite.vm` installs a lot of tools, but only each shortcut is broken since it does not have python in its `Target`.

For the python ones, I defaulted to using the icon from `python.exe`, and I will also write a fix for the `didier-stevens-beta/suite.vm` packages so that the shortcuts work out of the box.
