### ISSUE TITLE
Remove Google Chrome lnk in Desktop

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#820]
### Details

Deleting the Google Chrome shortcut in the Desktop created by `googlechrome.vm` seems to be tricky. Google Chrome creates an initial link in `%Public%\Desktop\Google Chrome.lnk` that is easy to delete. If we delete that link during the installation another link is created later at `%UserProfile\Desktop\Google Chrome.lnk`. This second link seems to appear when opening Chrome or when running `Stop-Process -Name explorer -Force`.

Any ideas how to get rid of this shortcuts?

See https://github.com/mandiant/VM-Packages/pull/779#discussion_r1423851641

**Comment by day1player** [comment]
That is some really interesting behavior.. I think we should create a function `VM-Remove-Desktop-Shortcut` which we could use both during the install, and then optionally call the function again at the end of the install when the config changes are made?

**Comment by emtuls** [comment]
I believe this is mostly fixed now from the last chrome PR: https://github.com/mandiant/VM-Packages/pull/978

I think the creation of the "First Run" file probably mitigated the annoying one that popped up when you run chrome.

The other one that is created during installation is something I will add to my latest Chrome PR, since it is just removing the shortcut from `Public\Desktop`: https://github.com/mandiant/VM-Packages/pull/1016
