### ISSUE TITLE
Blobrunner64.vm Fails Due to Checksum mismatch

### ISSUE THREAD

**Issue by Rebeccad316** [mandiant/VM-Packages#874]
### What's the problem?

This is the error message that I receive:

<img width="830" alt="image" src="https://github.com/mandiant/VM-Packages/assets/52222037/1013f849-f8af-4dac-adee-821325ecbb02">

I did a sha256 on the file and got the following result, which confirms the mismatch:

<img width="431" alt="image" src="https://github.com/mandiant/VM-Packages/assets/52222037/327233b6-4a53-495b-9bfe-5e8a90de1e40">

Thank you for your help with this issue btw!

### Steps to Reproduce

1. Run the install.ps1 file after a few system restarts, it will have an issue running blob runner and state that the download failed due to a checksum mismatch.

### Environment

-Virtualization software: VIrtual Box
-VM OS version: 10.0.19045
-VM Powershell Version 5.1.19041.1682
-VM Chocolatey version: 2.2.2
-VM Boxstarter version: 3.0.3

### Detected by test suite

No

**Comment by emtuls** [comment]
Hello @Rebeccad316! Thank you for the report.

1. I am seeing that in your first screenshot, it looks like the download for `blobrunner64` may have been blocked based on the comment: `Unhandled Exception: System.IO.IOException: Operation did not complete successfully because the file contains a virus or potentially unwanted software`

- Do you by chance still have Windows Defender running or not fully disabled?
- When I attempt to download `blobrunner64`, I do get an issue that "this file may contain a virus or potentially unwanted software" (as seen in the screenshot below).

![image](https://github.com/mandiant/VM-Packages/assets/35854880/527e9cfa-bf5a-47a5-a4c2-d2a870bf44e8)


2. The sha256 checksum that you ran for `blobrunner` in your second screenshot is for the 32 bit version of the program, which is called `blobrunner` as opposed to `blobrunner64`, which matches the checksum here: https://github.com/mandiant/VM-Packages/blob/main/packages/blobrunner.vm/tools/chocolateyinstall.ps1#L8

Downloading `blobrunner64` and running a sha256 checksum on it, I do get the proper checksum as noted here: https://github.com/mandiant/VM-Packages/blob/main/packages/blobrunner64.vm/tools/chocolateyinstall.ps1#L8
![image](https://github.com/mandiant/VM-Packages/assets/35854880/75ba3081-74c9-40eb-bdae-5ea44b013345)

**Comment by Ana06** [comment]
@Rebeccad316 has @emtuls' answer help resolving the problem? can we close this issue?

**Comment by Rebeccad316** [comment]
Hello Ana,

Yes the issue can be closed. I was able to get a proper checksum thanks to
emtuls remarks.

Thank you again for your help,

-Rebeca
