### ISSUE TITLE
VM-Clean-Up - fix sort Desktop icons

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#974]
### Details

I have encountered two issues with `VM-Clean-Up`:
- When sorting the Desktop icons by type, if they are already sorted, they are sorted by type in reverse order. This causes the VM to look different depending how the icons were sorted and it is a problem to distribute builds that look the same.
- When running `VM-Clean-Up` from a PowerShell tab in the Windows Terminal, the icons are not sorted. Does maybe increasing the time we wait fixes this? Do we need to document to run this from PowerShell and not from the Windows Terminal?

@emtuls ideas?

**Comment by emtuls** [comment]
After many hours of testing various things, I finally found a solution that works for both standard Powershell and Windows-Terminal Powershell. 😊

Regular Powershell is a little bit easier, since when we perform `(New-Object -ComObject Shell.Application).toggleDesktop();`, it automatically brings the focus to the desktop, whereas with Windows-Terminal, it doesn't.

The general sorting solution ended up just being to sort by Name first, then by Item Type. Testing various ways does seem to work how we would like.

The only maybe more ideal way would be to have `Tools` folder just under the `Recycle Bin`, but this was the best I could get.
